employees=[{"eid":1,"ename":"Gustavus","gender":"Male"},
{"eid":2,"ename":"Byran","gender":"Male"},
{"eid":3,"ename":"Dorian","gender":"Male"},
{"eid":4,"ename":"Hersch","gender":"Male"},
{"eid":5,"ename":"Huntley","gender":"Male"},
{"eid":6,"ename":"Delcina","gender":"Female"},
{"eid":7,"ename":"Sansone","gender":"Male"},
{"eid":8,"ename":"Trev","gender":"Male"},
{"eid":9,"ename":"Nickola","gender":"Male"},
{"eid":10,"ename":"Kittie","gender":"Female"},
{"eid":11,"ename":"Theodor","gender":"Male"},
{"eid":12,"ename":"Ekaterina","gender":"Female"},
{"eid":13,"ename":"Marigold","gender":"Agender"},
{"eid":14,"ename":"Artemus","gender":"Male"},
{"eid":15,"ename":"Westbrook","gender":"Male"},
{"eid":16,"ename":"Jemmy","gender":"Bigender"},
{"eid":17,"ename":"Zaria","gender":"Female"},
{"eid":18,"ename":"Fran","gender":"Female"},
{"eid":19,"ename":"Adella","gender":"Female"},
{"eid":20,"ename":"Carmine","gender":"Male"},
{"eid":21,"ename":"Selle","gender":"Female"},
{"eid":22,"ename":"D'arcy","gender":"Male"},
{"eid":23,"ename":"Christen","gender":"Female"},
{"eid":24,"ename":"Pepita","gender":"Female"},
{"eid":25,"ename":"Nertie","gender":"Genderqueer"},
{"eid":26,"ename":"Marlin","gender":"Male"},
{"eid":27,"ename":"Rodie","gender":"Female"},
{"eid":28,"ename":"Dexter","gender":"Male"},
{"eid":29,"ename":"Aaren","gender":"Bigender"},
{"eid":30,"ename":"Mahalia","gender":"Female"},
{"eid":31,"ename":"Stu","gender":"Male"},
{"eid":32,"ename":"Kellby","gender":"Male"},
{"eid":33,"ename":"Nancie","gender":"Female"},
{"eid":34,"ename":"Bonnee","gender":"Non-binary"},
{"eid":35,"ename":"Fairleigh","gender":"Male"},
{"eid":36,"ename":"Gerti","gender":"Female"},
{"eid":37,"ename":"Siana","gender":"Polygender"},
{"eid":38,"ename":"Osbourne","gender":"Male"},
{"eid":39,"ename":"Celinda","gender":"Female"},
{"eid":40,"ename":"Cloris","gender":"Female"},
{"eid":41,"ename":"Cirillo","gender":"Male"},
{"eid":42,"ename":"Lenci","gender":"Male"},
{"eid":43,"ename":"Sean","gender":"Female"},
{"eid":44,"ename":"Issie","gender":"Female"},
{"eid":45,"ename":"Chrysler","gender":"Female"},
{"eid":46,"ename":"Iormina","gender":"Female"},
{"eid":47,"ename":"Karney","gender":"Male"},
{"eid":48,"ename":"Linnie","gender":"Female"},
{"eid":49,"ename":"Delbert","gender":"Male"},
{"eid":50,"ename":"Kile","gender":"Male"}]

male_Count=0
for emp in employees:
    if emp["gender"] == "Male":
        male_Count += 1
print("no of Male emp",male_Count)